In [1]:
import numpy as np


In [2]:
a=[1,22,33,4,15]
print(a)
print(type(a))


[1, 22, 33, 4, 15]
<class 'list'>


In [3]:
b=a[2:]
print(b)

[33, 4, 15]


In [4]:
b[1]=400
print(b)

[33, 400, 15]


In [5]:
print(a)

[1, 22, 33, 4, 15]


In [6]:
c=np.array([1,22,33,4,15])
d=c[2:]


In [7]:
d[1]=400
print(d)

[ 33 400  15]


In [8]:
a=np.array(12) ##0d  jitne square honge utne d array ye 0d he
a


array(12)

In [9]:

print(a.ndim)

0


In [10]:
a.shape


()

In [11]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [12]:
b.ndim ##dimension batata he 

1

In [13]:
b.shape ##total no of elements

(5,)

In [14]:
b.size

5

In [15]:
len(b)

5

In [16]:
c=np.array([[12]])
c

array([[12]])

In [17]:
c.ndim

2

In [18]:
c.shape

(1, 1)

In [19]:
d=np.array([[1,2,3],[4,5,6]]) ##[1,2,3]ek row or dusro [4,5,6]
d

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
d.ndim ##last kitne box he [] ye wale uska dimension

2

In [21]:
d.shape ##rows and coloumns in 2d 

(2, 3)

In [22]:

info = np.array([
    ['id', 'name', 'age'],
    [1, 'a', 10],
    [2, 'b', 11],
    [3, 'C', 12]
])

In [23]:
print(info.shape)
print(info.size)

(4, 3)
12


In [24]:
b=np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]],
    [[13,14,15],
     [16,17,18]]
])

In [25]:
b.ndim

3

In [26]:
b.shape ##kitne array he 3d k andar tu 2 d array he woh bhi 3 hee ek ke andar 2 row 3 coloumn 3 two dimensional arrays fir 2 rows fir 3 coloumn wu output diya

(3, 2, 3)

In [27]:
a=np.array([12],ndmin=3)
print(a) ##min dimension 3 isse zyads kitne bhi hosktehe 

[[[12]]]


In [28]:
a=np.array([12],ndmin=60)
print(a)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[12]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [29]:
info = np.array([
    ['id', 'name', 'age'],
    [1, 'a', 10],
    [2, 'b', 11],
    [3, 'C', 12]
])

In [30]:
info[1,1]##phele rows ka fir coloumn ko
info[1,1]='Z'
info

array([['id', 'name', 'age'],
       ['1', 'Z', '10'],
       ['2', 'b', '11'],
       ['3', 'C', '12']], dtype='<U21')

In [31]:
info[2][1:]

array(['b', '11'], dtype='<U21')

In [32]:
info[2:]

array([['2', 'b', '11'],
       ['3', 'C', '12']], dtype='<U21')

arange

In [33]:
##arange
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
b=np.arange(10,101,10)
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [35]:
c=np.arange(10,-1,-2)
c

array([10,  8,  6,  4,  2,  0])

In [36]:
a=np.arange(1,11,3)
a ##start at 1 go to 4 then 7 stop before 11 go till 10

array([ 1,  4,  7, 10])

In [37]:
a=np.linspace(1,10,3)
a ##divides in equal number 10 is also included

array([ 1. ,  5.5, 10. ])

In [38]:
d=np.linspace(-10,-5,5)
d


array([-10.  ,  -8.75,  -7.5 ,  -6.25,  -5.  ])

zeros and ones

In [39]:
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [40]:
b=np.zeros((5,5)) ##rows,coloumns
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
b=np.ones((2,2),dtype=int) ##int kr diya datatype
b

array([[1, 1],
       [1, 1]])

In [42]:
b=np.ones((2,2),dtype=bool) ##bool kr diya datatype
b

array([[ True,  True],
       [ True,  True]])

full

In [43]:
a=np.full((3,3),11) ##sare rows coloumn me 11 de diya 
a

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

eye

In [44]:
a=np.eye(5) ##rows coloumn equal ho jaye 
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

diag

In [45]:
a=np.diag([1,2,3,4,5]) ##arr pass kr do wu arr diagnol me aajayega
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

operators

In [46]:
a=np.array([1,2,3])
a+10

array([11, 12, 13])

In [47]:
a>4

array([False, False, False])

In [48]:
a==3

array([False, False,  True])

Boolean indexing

In [49]:
a=np.arange(1,15,3)
a

array([ 1,  4,  7, 10, 13])

In [50]:
a>5

array([False, False,  True,  True,  True])

In [51]:
a[a>5] ##no mil gya ye booolean indexing he 

array([ 7, 10, 13])

In [52]:
a[a%2==0]

array([ 4, 10])

In [ ]:
a=[1,2,3,4,5]
b=[6,7,8,9,10] ##list me peeche jod deta he arr ko
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b ##arr me direct jod deta he 

array([5, 7, 9])

In [58]:
info=np.array(['a','b','c','a'])
info

array(['a', 'b', 'c', 'a'], dtype='<U1')

In [61]:
info[info=='a'].size

2

any,all,arr_equal

In [62]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
ages=np.array([18,19,20,21])
ages

array([18, 19, 20, 21])

In [ ]:
np.any(ages>18) ##agar ek bhi value 18 se bdi tu true dega 

np.True_

In [ ]:
np.all(ages>18) ##sari value 18 se badi hogi tu true dega 

np.False_

In [66]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a==b

array([ True,  True,  True,  True])

In [ ]:
np.array_equal(a,b) ##pura array dekhega ki same he ki nahi 

True

In [72]:
a=np.array([
    [54,89,90],
    [45,73,32],
    [80,29,43],
    [20,38,32]
])
a

array([[54, 89, 90],
       [45, 73, 32],
       [80, 29, 43],
       [20, 38, 32]])

aggegrate functions

In [73]:
np.sum(a)

np.int64(625)

In [74]:
np.min(a)

np.int64(20)

In [76]:
np.max(a)

np.int64(90)

In [78]:
np.mean(a)

np.float64(52.083333333333336)

In [ ]:
np.median(a) ##isme mode hota hi nahi he

np.float64(44.0)

In [83]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [84]:
np.std(a)

np.float64(2.8722813232690143)

In [ ]:
b=np.arange(1,14) ##kitne space me fela hua is std b me dekho range bdha di tu badh gya kyuki zyada range zyada space me faili he
np.std(b)

np.float64(3.7416573867739413)