In [306]:
import numpy as np


In [307]:
a=[1,22,33,4,15]
print(a)
print(type(a))


[1, 22, 33, 4, 15]
<class 'list'>


In [308]:
b=a[2:]
print(b)

[33, 4, 15]


In [309]:
b[1]=400
print(b)

[33, 400, 15]


In [310]:
print(a)

[1, 22, 33, 4, 15]


In [311]:
c=np.array([1,22,33,4,15])
d=c[2:]


In [312]:
d[1]=400
print(d)

[ 33 400  15]


In [313]:
a=np.array(12) ##0d  jitne square honge utne d array ye 0d he
a


array(12)

In [314]:

print(a.ndim)

0


In [315]:
a.shape


()

In [316]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [317]:
b.ndim ##dimension batata he 

1

In [ ]:
b.shape ##total no of elements 1 d arr he tu 

(5,)

In [319]:
b.size

5

In [320]:
len(b)

5

In [321]:
c=np.array([[12]])
c

array([[12]])

In [322]:
c.ndim

2

In [323]:
c.shape

(1, 1)

In [324]:
d=np.array([[1,2,3],[4,5,6]]) ##[1,2,3]ek row or dusro [4,5,6]
d

array([[1, 2, 3],
       [4, 5, 6]])

In [325]:
d.ndim ##last kitne box he [] ye wale uska dimension

2

In [326]:
d.shape ##rows and coloumns in 2d 

(2, 3)

In [327]:

info = np.array([
    ['id', 'name', 'age'],
    [1, 'a', 10],
    [2, 'b', 11],
    [3, 'C', 12]
])

In [328]:
print(info.shape)
print(info.size)

(4, 3)
12


In [329]:
b=np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]],
    [[13,14,15],
     [16,17,18]]
])

In [330]:
b.ndim

3

In [331]:
b.shape ##kitne array he 3d k andar tu 2 d array he woh bhi 3 hee ek ke andar 2 row 3 coloumn 3 two dimensional arrays fir 2 rows fir 3 coloumn wu output diya

(3, 2, 3)

In [332]:
a=np.array([12],ndmin=3)
print(a) ##min dimension 3 isse zyads kitne bhi hosktehe 

[[[12]]]


In [333]:
a=np.array([12],ndmin=60)
print(a)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[12]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [334]:
info = np.array([
    ['id', 'name', 'age'],
    [1, 'a', 10],
    [2, 'b', 11],
    [3, 'C', 12]
])

In [335]:
info[1,1]##phele rows ka fir coloumn ko
info[1,1]='Z'
info

array([['id', 'name', 'age'],
       ['1', 'Z', '10'],
       ['2', 'b', '11'],
       ['3', 'C', '12']], dtype='<U21')

In [336]:
info[2][1:]

array(['b', '11'], dtype='<U21')

In [337]:
info[2:]

array([['2', 'b', '11'],
       ['3', 'C', '12']], dtype='<U21')

arange

In [338]:
##arange
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [339]:
b=np.arange(10,101,10)
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [340]:
c=np.arange(10,-1,-2)
c

array([10,  8,  6,  4,  2,  0])

In [341]:
a=np.arange(1,11,3)
a ##start at 1 go to 4 then 7 stop before 11 go till 10

array([ 1,  4,  7, 10])

In [342]:
a=np.linspace(1,10,3)
a ##divides in equal number 10 is also included

array([ 1. ,  5.5, 10. ])

In [343]:
d=np.linspace(-10,-5,5)
d


array([-10.  ,  -8.75,  -7.5 ,  -6.25,  -5.  ])

zeros and ones

In [344]:
a=np.zeros((2,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [345]:
b=np.zeros((5,5)) ##rows,coloumns
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [346]:
b=np.ones((2,2),dtype=int) ##int kr diya datatype
b

array([[1, 1],
       [1, 1]])

In [347]:
b=np.ones((2,2),dtype=bool) ##bool kr diya datatype
b

array([[ True,  True],
       [ True,  True]])

full

In [348]:
a=np.full((3,3),11) ##sare rows coloumn me 11 de diya 
a

array([[11, 11, 11],
       [11, 11, 11],
       [11, 11, 11]])

eye

In [349]:
a=np.eye(5) ##rows coloumn equal ho jaye 
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

diag

In [350]:
a=np.diag([1,2,3,4,5]) ##arr pass kr do wu arr diagnol me aajayega
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

operators

In [351]:
a=np.array([1,2,3])
a+10

array([11, 12, 13])

In [352]:
a>4

array([False, False, False])

In [353]:
a==3

array([False, False,  True])

Boolean indexing

In [354]:
a=np.arange(1,15,3)
a

array([ 1,  4,  7, 10, 13])

In [355]:
a>5

array([False, False,  True,  True,  True])

In [356]:
a[a>5] ##no mil gya ye booolean indexing he 

array([ 7, 10, 13])

In [357]:
a[a%2==0]

array([ 4, 10])

In [358]:
a=[1,2,3,4,5]
b=[6,7,8,9,10] ##list me peeche jod deta he arr ko
a+b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [359]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b ##arr me direct jod deta he 

array([5, 7, 9])

In [360]:
info=np.array(['a','b','c','a'])
info

array(['a', 'b', 'c', 'a'], dtype='<U1')

In [361]:
info[info=='a'].size

2

any,all,arr_equal

In [362]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [363]:
ages=np.array([18,19,20,21])
ages

array([18, 19, 20, 21])

In [364]:
np.any(ages>18) ##agar ek bhi value 18 se bdi tu true dega 

np.True_

In [365]:
np.all(ages>18) ##sari value 18 se badi hogi tu true dega 

np.False_

In [366]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
a==b

array([ True,  True,  True,  True])

In [367]:
np.array_equal(a,b) ##pura array dekhega ki same he ki nahi 

True

In [368]:
a=np.array([
    [54,89,90],
    [45,73,32],
    [80,29,43],
    [20,38,32]
])
a

array([[54, 89, 90],
       [45, 73, 32],
       [80, 29, 43],
       [20, 38, 32]])

aggegrate functions

In [369]:
np.sum(a)

np.int64(625)

In [370]:
np.min(a)

np.int64(20)

In [371]:
np.max(a)

np.int64(90)

In [372]:
np.mean(a)

np.float64(52.083333333333336)

In [373]:
np.median(a) ##isme mode hota hi nahi he

np.float64(44.0)

In [374]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [375]:
np.std(a)

np.float64(2.8722813232690143)

In [376]:
b=np.arange(1,14) ##kitne space me fela hua is std b me dekho range bdha di tu badh gya kyuki zyada range zyada space me faili he
np.std(b)

np.float64(3.7416573867739413)

In [377]:
a=np.array([
    ["name","p","c","m"],
    ["a",39,40,50],
     ["b",20,30,20],
    ["c",30,40,30],
   ["d",40,50,50],
])

In [378]:
a

array([['name', 'p', 'c', 'm'],
       ['a', '39', '40', '50'],
       ['b', '20', '30', '20'],
       ['c', '30', '40', '30'],
       ['d', '40', '50', '50']], dtype='<U21')

In [379]:
b=np.array([
    [10,20,30],
    [20,30,40],
    [40,50,60],
])

In [380]:
np.sum(b)

np.int64(300)

In [381]:
np.sum(b,axis=1) ##coloumn wise sum k liye 10+20+30=60 pheli row ki value me dusra fir teesra joda 

array([ 60,  90, 150])

In [382]:
np.sum(b,axis=0) ##row wise sum k liye

array([ 70, 100, 130])

In [383]:
c=a[1:,1].astype(int)

In [384]:
np.sum(c)

np.int64(129)

In [385]:
np.cumsum(b)

array([ 10,  30,  60,  80, 110, 150, 190, 240, 300])

In [386]:
np.cumsum(b,axis=1) ##sbka cum sum kr dega 10+20=30 30+30=60 60+20=80

array([[ 10,  30,  60],
       [ 20,  50,  90],
       [ 40,  90, 150]])

In [387]:
np.cumsum(b,axis=0)

array([[ 10,  20,  30],
       [ 30,  50,  70],
       [ 70, 100, 130]])

In [388]:
np.cumprod(b) ##sum jaise hi product kr diya 

array([            10,            200,           6000,         120000,
              3600000,      144000000,     5760000000,   288000000000,
       17280000000000])

Concatenate

In [389]:
a=np.arange(1,7).reshape(2,3) ##reshape me rows  and coloumns de do waise shape me kr dete he 2 rows 3 coloumns
a

array([[1, 2, 3],
       [4, 5, 6]])

In [390]:
b=np.arange(-6,0).reshape(2,3)
b

array([[-6, -5, -4],
       [-3, -2, -1]])

In [391]:
np.concatenate((a,b))##by  default row wise no of rows badh jyegi  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-6, -5, -4],
       [-3, -2, -1]])

In [392]:
np.concatenate((a,b),axis=1) ##coloumn wise coloumns badh jyenge 

array([[ 1,  2,  3, -6, -5, -4],
       [ 4,  5,  6, -3, -2, -1]])

In [393]:
np.concatenate((a,b),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [-6, -5, -4],
       [-3, -2, -1]])

split

In [394]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [395]:
np.split(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [396]:
np.split(a.reshape(6,),3)

[array([1, 2]), array([3, 4]), array([5, 6])]

vsplit hsplit

In [397]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [398]:
np.array_split(a,4)

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [399]:
np.hsplit(a,3) ##dekho na 1,4 toda 2,5 toda or 3,6 toda 

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [400]:
np.vsplit(a,2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [401]:
a=np.append(a,7) ###last me jod deta he
a

array([1, 2, 3, 4, 5, 6, 7])

In [402]:
a=np.insert(a,3,0) ##insert kr diya 3 index pe 
a

array([1, 2, 3, 0, 4, 5, 6, 7])

In [403]:
np.delete(a,3) ##0 hat gya

array([1, 2, 3, 4, 5, 6, 7])

In [404]:

arr = np.array([1, 2, 5, 6])

arr = np.insert(arr, 2, [3, 4])
arr ##multiple values innsert kra di 

array([1, 2, 3, 4, 5, 6])

In [405]:
a=np.arange(1,7)

In [406]:

a=np.arange(1,7).reshape(3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.delete(a,1,axis=0) ##delete kr diya 1 row ko

array([[1, 2],
       [5, 6]])

In [408]:
a=np.arange(1,20,3)
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
a[a%2!=0] 

array([ 1,  7, 13, 19])

where

In [411]:
a

array([ 1,  4,  7, 10, 13, 16, 19])

In [ ]:
np.where(a>10,"high","low") ##if jaisa hi kaam krega ye 

array(['low', 'low', 'low', 'low', 'high', 'high', 'high'], dtype='<U4')

In [416]:
np.where(a%2==0,"even","odd")

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')