In [21]:
import numpy as np


In [22]:
a=[1,22,33,4,15]
print(a)
print(type(a))


[1, 22, 33, 4, 15]
<class 'list'>


In [23]:
b=a[2:]
print(b)

[33, 4, 15]


In [24]:
b[1]=400
print(b)

[33, 400, 15]


In [25]:
print(a)

[1, 22, 33, 4, 15]


In [26]:
c=np.array([1,22,33,4,15])
d=c[2:]


In [27]:
d[1]=400
print(d)

[ 33 400  15]


In [28]:
a=np.array(12) ##0d  jitne square honge utne d array ye 0d he
a


array(12)

In [29]:

print(a.ndim)

0


In [30]:
a.shape


()

In [31]:
b=np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [ ]:
b.ndim ##dimension batata he 

1

In [33]:
b.shape ##total no of elements

(5,)

In [34]:
b.size

5

In [35]:
len(b)

5

In [36]:
c=np.array([[12]])
c

array([[12]])

In [37]:
c.ndim

2

In [38]:
c.shape

(1, 1)

In [ ]:
d=np.array([[1,2,3],[4,5,6]]) ##[1,2,3]ek row or dusro [4,5,6]
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d.ndim ##last kitne box he [] ye wale uska dimension

2

In [ ]:
d.shape ##rows and coloumns in 2d 

(2, 3)

In [47]:

info = np.array([
    ['id', 'name', 'age'],
    [1, 'a', 10],
    [2, 'b', 11],
    [3, 'C', 12]
])

In [49]:
print(info.shape)
print(info.size)

(4, 3)
12


In [53]:
b=np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]],
    [[13,14,15],
     [16,17,18]]
])

In [56]:
b.ndim

3

In [ ]:
b.shape ##kitne array he 3d k andar tu 2 d array he woh bhi 3 hee ek ke andar 2 row 3 coloumn 3 two dimensional arrays fir 2 rows fir 3 coloumn wu output diya

(3, 2, 3)

In [ ]:
a=np.array([12],ndmin=3)
print(a) ##min dimension 3 isse zyads kitne bhi hosktehe 

[[[12]]]


In [60]:
a=np.array([12],ndmin=60)
print(a)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[12]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [61]:
info = np.array([
    ['id', 'name', 'age'],
    [1, 'a', 10],
    [2, 'b', 11],
    [3, 'C', 12]
])

In [71]:
info[1,1]##phele rows ka fir coloumn ko
info[1,1]='Z'
info

array([['id', 'name', 'age'],
       ['1', 'Z', '10'],
       ['2', 'b', '11'],
       ['3', 'C', '12']], dtype='<U21')

In [72]:
info[2][1:]

array(['b', '11'], dtype='<U21')

In [79]:
info[2:]

array([['2', 'b', '11'],
       ['3', 'C', '12']], dtype='<U21')