In [2]:
import numpy as np


In [ ]:
arr=np.array([1,2,3,4]) ##aise array bnate he numpy pe
arr

array([1, 2, 3, 4])

In [ ]:
arr=np.arange(1,11)##range jaisa hi kaam krega 1 se 11 di tu 11-1=10 tk jyega
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr=np.zeros((4,8))## phela row dusra coloumn
arr


array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr=np.ones((6,12)) ##one print krega 6 rows and 12 coloums
arr 

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
arr=np.linspace(1,2,100)  ##sbke beech same space dega 
arr


array([1.        , 1.01010101, 1.02020202, 1.03030303, 1.04040404,
       1.05050505, 1.06060606, 1.07070707, 1.08080808, 1.09090909,
       1.1010101 , 1.11111111, 1.12121212, 1.13131313, 1.14141414,
       1.15151515, 1.16161616, 1.17171717, 1.18181818, 1.19191919,
       1.2020202 , 1.21212121, 1.22222222, 1.23232323, 1.24242424,
       1.25252525, 1.26262626, 1.27272727, 1.28282828, 1.29292929,
       1.3030303 , 1.31313131, 1.32323232, 1.33333333, 1.34343434,
       1.35353535, 1.36363636, 1.37373737, 1.38383838, 1.39393939,
       1.4040404 , 1.41414141, 1.42424242, 1.43434343, 1.44444444,
       1.45454545, 1.46464646, 1.47474747, 1.48484848, 1.49494949,
       1.50505051, 1.51515152, 1.52525253, 1.53535354, 1.54545455,
       1.55555556, 1.56565657, 1.57575758, 1.58585859, 1.5959596 ,
       1.60606061, 1.61616162, 1.62626263, 1.63636364, 1.64646465,
       1.65656566, 1.66666667, 1.67676768, 1.68686869, 1.6969697 ,
       1.70707071, 1.71717172, 1.72727273, 1.73737374, 1.74747

In [ ]:
np.random.rand(5)##5 random values aajyengi sb value 0 se 1 tk hi aayegi isko normalisation hoga

array([0.78959002, 0.34486131, 0.46455624, 0.42146092, 0.75261306])

In [ ]:
np.random.randn(10) ## ye -3 se 3 tk jyega 

array([-0.55664713, -0.0749646 ,  0.83588765, -1.58126009, -0.19616208,
       -0.56452644, -0.20967307,  1.65916953,  0.57687555, -0.44873079])

In [ ]:
np.random.randint(10,20,5)## 10 se 20 ke beech 5 no random genrate kr diye

array([10, 13, 10, 18, 18], dtype=int32)

In [54]:
##2d arr
arr=np.array([[1,2,3],[6,7,11],[8,9,10]])
arr

array([[ 1,  2,  3],
       [ 6,  7, 11],
       [ 8,  9, 10]])

In [ ]:
arr.shape ##ye ek attribute he 3 rows 3 coloums ye shape bta rha  he attribute ke sath () nhi lgta 

(3, 3)

In [ ]:
arr.size ##no of elements in array


12

In [ ]:
arr.dtype #ye bhi attribute he

dtype('int64')

In [48]:
arr.max()
int(arr.max())

14

In [47]:
arr.min()

np.int64(1)

In [56]:
arr.sum()

np.int64(57)

In [ ]:
np.sum(arr,axis=1) ##isne row wise add kr diya kyuki axis 1 he
##1 mtlb row

array([20, 35, 38])

In [52]:
int(arr.mean())

7

In [55]:
arr.argmax()

np.int64(5)

In [57]:
arr.argmin()

np.int64(0)

In [ ]:
arr=np.arange(1,31)
arr   ##reshape se apne hisab se rows coloumn me dal diya
arr.reshape(6,5) 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [5]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[1:5] ##12 se 15 tk slice kra diya 

array([12, 13, 14, 15])

In [ ]:
arr[:5] ##shuru wala default zero ho gya

array([11, 12, 13, 14, 15])

In [ ]:
arr[1:]##1 se end tk ho jyega

In [ ]:
arr[3::2] ##3 pe gya fir wha se 2 ka jump lene laga

array([14, 16, 18, 20])

In [15]:
arr=np.arange(1,31)
arr1=arr.reshape(6,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr1[4,3] ##4 row pe jake 3 coloumn ko acccess kiya tu aaya 24 
##yaad rkh row or coloum 0  se chalu honge

np.int64(24)

In [21]:
arr1[5,-1]

np.int64(30)

In [ ]:
arr1[3:6,3:5] ##0  se chalu kiya dekha 19 tha 3 row pe 6 likha mtlb 5 row tk jyega fir coloumn dekha 3 coloumn pe he and 5 tk gye tu 4 tk jyega 

array([[19, 20],
       [24, 25],
       [29, 30]])

In [23]:
arr1[2:4,2:4]

array([[13, 14],
       [18, 19]])

In [24]:
arr1[4:6,3:]

array([[24, 25],
       [29, 30]])

In [26]:
arr1=np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
arr1[1::2]

array([12, 14, 16, 18, 20])

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10]) ##dono ke element add ho gye dono me same no of elements hone chahiye aise hi  minus multiply bhi  kr skte he 
a1+a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1=np.array([1,2,3,4,5])
a2=a1+10
a2 ##broadcasting sb me 10 add ho gya list me loop me hota he 

array([11, 12, 13, 14, 15])

In [ ]:
a=np.arange(1,21)
b=a[0:5]
c=10*b ##slice krke change kra tu maine a me koyi changes nahi aayenge 
c

array([10, 20, 30, 40, 50])

In [ ]:
a=np.arange(1,21)
b=a
b[0]=99
b ##dekho ab a ko puraa b me copy kraya slice nahi kiya pura 
##copy kraya tu ab change a me bhi hoga dono me changes hoga agar pura copy kra 
##he tu isko deep copy khenge b ke change a m bhi jynge


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a  ##dekha a me bhi chanage hua
d=np.arange(10,20)##ye ho jyega shallow copy ab me ke changes a me nahi jyenge
e=d.copy()
e[0]=1000
e

array([1000,   11,   12,   13,   14,   15,   16,   17,   18,   19])

In [ ]:
d  ## dekho d me koyi changes nahi he isko bolyte he shallow copy kyuki d ke baad copy use 
##kr diye

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
A=np.array([[1,2],[3,4]])
B=np.array([[6,7],[8,9]])
A*B 

array([[ 6, 14],
       [24, 36]])